---
- name: Hello world
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Connectivity check
      ansible.builtin.shell:
        cmd: "{{ hello_world_command }}"
      register: check
      changed_when: false

    - name: Display connectivity check
      ansible.builtin.debug:
        msg: "{{ check.stdout }}"
