[dev-1]
dev-1-alpine-01 ansible_host=192.168.10.137 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ev1_app environment_name=dev-1 pve_node=pve1 vm_id=102

[dev-1:vars]
ansible_python_interpreter=/usr/bin/python3
